import test from 'node:test';
import assert from 'node:assert/strict';
import { masteryStart, startLabel } from '../lib/learning/mastery-gate.js';

/*
 * The defect this was written for. A course generated by this product has no
 * mastery plan -- nothing in the drafting pipeline makes one -- and the learner
 * screen required an APPROVED plan before it would enable the button. So the
 * one place a learner writes in their own words was unreachable from every
 * course the system itself produced, while the server it calls would have
 * started the session happily.
 */
test('a course with no mastery plan can still be practised', () => {
  const gate = masteryStart(null, 'source-1');
  assert.equal(gate.allowed, true);
  assert.equal(gate.tone, 'info', 'a plainer session is not a broken one');
  assert.match(gate.reason, /objectives/i);
});

test('an approved plan is what the session is graded on', () => {
  const gate = masteryStart({ status: 'APPROVED', sourceId: 'source-1' }, 'source-1');
  assert.equal(gate.allowed, true);
  assert.match(gate.reason, /approved rubric/i);
});

// The server refuses this one, so the button must too -- and must say who can
// clear it, because the learner cannot.
test('a pending plan blocks, and names the person who can unblock it', () => {
  const gate = masteryStart({ status: 'PENDING', sourceId: 'source-1' }, 'source-1');
  assert.equal(gate.allowed, false);
  assert.match(gate.reason, /instructor/i);
});

test('a plan in no recognised state blocks rather than being treated as absent', () => {
  for (const status of ['DRAFT', 'REJECTED', '', undefined]) {
    const gate = masteryStart({ status, sourceId: 'source-1' }, 'source-1');
    assert.equal(gate.allowed, false, `status ${String(status)}`);
  }
});

// startMastery throws notFound('Source is not the approved mastery-plan
// source'). A disabled button with a sentence beats a 404 after a click.
test('an approved plan for a different source blocks before the request is made', () => {
  const gate = masteryStart({ status: 'APPROVED', sourceId: 'source-2' }, 'source-1');
  assert.equal(gate.allowed, false);
  assert.match(gate.reason, /different source/i);
});

test('no source at all is the one refusal that is about the course, not the plan', () => {
  const gate = masteryStart({ status: 'APPROVED' }, null);
  assert.equal(gate.allowed, false);
  assert.match(gate.reason, /no approved source/i);
});

test('a malformed plan value is treated as no plan rather than crashing the screen', () => {
  for (const plan of [[], 'APPROVED', 7]) {
    assert.equal(masteryStart(plan, 'source-1').allowed, true, JSON.stringify(plan));
  }
});

test('the button says what it will grade on', () => {
  assert.match(startLabel({ status: 'APPROVED' }), /approved plan/i);
  assert.equal(startLabel(null), 'Start mastery session');
  assert.equal(startLabel({ status: 'PENDING' }), 'Start mastery session');
});
