import Shell from "@/app/_components/Shell";
import { prisma } from "@/lib/db";
import { sampleCourse } from "@/lib/sample";

export const dynamic = "force-dynamic";

async function loadCourse() {
  const course = await prisma.course.findFirst({
    include: { sections: { orderBy: { order: "asc" }, include: { items: true } } },
  });
  if (!course) throw new Error("no course seeded");
  return course;
}

function citeText(c) {
  if (!c) return null;
  return typeof c === "string" ? c : c.citation || null;
}

function pill(status) {
  const cls = status === "APPROVED" ? "approved" : status === "REJECTED" ? "rejected" : "pending";
  return <span className={"statepill " + cls}>{status}</span>;
}

export default async function StudioPage() {
  let course;
  let sample = false;
  try {
    course = await loadCourse();
  } catch {
    course = sampleCourse;
    sample = true;
  }

  const sections = course.sections || [];
  const pending = [];
  for (const s of sections) {
    for (const it of s.items || []) {
      if (it.status === "PENDING") pending.push({ ...it, sectionTitle: s.title });
    }
  }
  const totalItems = sections.reduce((n, s) => n + (s.items?.length || 0), 0);
  const approved = totalItems - pending.length - sections
    .flatMap((s) => s.items || [])
    .filter((i) => i.status === "REJECTED").length;

  return (
    <Shell
      role="INSTRUCTOR"
      active="studio"
      title={course.title}
      subtitle={`Studio — build, review, and ratify. Grounded in ${course.sourceId}. Nothing PENDING reaches a learner.`}
    >
      {sample && (
        <div className="banner">
          Sample mode — the database isn&apos;t set up yet. Run{" "}
          <code>docker compose up -d &amp;&amp; npm run db:migrate &amp;&amp; npm run db:seed</code> to see live data.
        </div>
      )}

      <div className="tiles">
        <div className="tile"><div className="tilelab">Items</div><div className="tileval">{totalItems}</div><div className="tilenote">across {sections.length} sections</div></div>
        <div className="tile"><div className="tilelab">Approved</div><div className="tileval good">{approved}</div><div className="tilenote">live to learners</div></div>
        <div className="tile"><div className="tilelab">Awaiting review</div><div className="tileval warn">{pending.length}</div><div className="tilenote">blocked until ratified</div></div>
      </div>

      {/* Review queue */}
      <div className="panel">
        <h3>Review queue</h3>
        <p className="sub">Generated by the grounded pipeline. Each item points at the paragraph it came from — approve, edit, or reject.</p>
        {pending.length === 0 && <p className="note">Nothing awaiting review.</p>}
        {pending.map((it) => (
          <div className="reviewitem" key={it.id}>
            <div className="item-top">
              <span className="item-kind">{it.kind}</span>
              <span className="cite">{it.sectionTitle}</span>
              {typeof it.support === "number" && (
                <span className="badge ok" title="HHEM support score">support {it.support.toFixed(2)}</span>
              )}
              {pill(it.status)}
            </div>
            <div className="txt" style={{ marginTop: ".4rem" }}>{it.stem}</div>
            {citeText(it.citation) && <div style={{ marginTop: ".4rem" }}><span className="cite">{citeText(it.citation)}</span></div>}
            <div className="btnrow">
              <button className="btn good sm" type="button">Approve</button>
              <button className="btn ghost sm" type="button">Edit</button>
              <button className="btn crit sm" type="button">Reject</button>
              <span className="note">review actions are wired in during the build</span>
            </div>
          </div>
        ))}
      </div>

      {/* Full course tree */}
      <div className="label">Course tree</div>
      <div className="tree">
        {sections.map((s, i) => (
          <section className="mod" key={s.id}>
            <div className="mod-h">
              <span className="mod-letter">{String.fromCharCode(65 + i)}</span>
              {s.title}
              <span className="mod-count">{(s.items || []).length} items</span>
            </div>
            <div className="mod-items">
              {(s.items || []).map((it) => (
                <article className="item" key={it.id}>
                  <div className="item-top">
                    <span className="item-kind">{it.kind}</span>
                    {citeText(it.citation) && <span className="cite">{citeText(it.citation)}</span>}
                    {pill(it.status)}
                  </div>
                  <div className="txt">{it.stem}</div>
                </article>
              ))}
            </div>
          </section>
        ))}
      </div>
    </Shell>
  );
}
