import { useEffect, useRef, useState } from 'react';
import { useLocation } from 'wouter';
const suggestions = [{ label: 'Sight alignment?', q: 'What is sight alignment?' }, { label: 'Fix trigger jerk?', q: 'How do I correct trigger jerk?' }, { label: 'Javelin range?', q: 'What is the maximum effective range of a Javelin missile?', refuse: true }];
type Message = { who: 'ai' | 'me'; text: string; refuse?: boolean; note?: boolean; reason?: string; meta?: string; citations?: { n?: number; citation?: string; pub_id?: string; page_printed?: string }[] };
export default function AskWidget() {
  const [pathname] = useLocation(); const inCourse = /^\/prototype\/course\/[^/]+/.test(pathname); const [open, setOpen] = useState(false); const [messages, setMessages] = useState<Message[]>([{ who: 'ai', text: 'Ask me anything from the marksmanship corpus — I answer with a citation, or say plainly when it isn’t covered.' }]); const [input, setInput] = useState(''); const [busy, setBusy] = useState(false); const chatRef = useRef<HTMLDivElement>(null); const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { if (open) window.setTimeout(() => inputRef.current?.focus(), 60); }, [open]);
  useEffect(() => { if (chatRef.current) chatRef.current.scrollTop = chatRef.current.scrollHeight; }, [messages, busy]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, []);
  useEffect(() => { document.documentElement.classList.toggle('scw-global-ask-open', open && inCourse); return () => document.documentElement.classList.remove('scw-global-ask-open'); }, [open, inCourse]);
  async function send(question?: string) { const q = (question ?? input).trim(); if (!q || busy) return; setInput(''); setMessages((items) => [...items, { who: 'me', text: q }]); setBusy(true); try { const response = await fetch('/api/doctrine', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ question: q }) }); const data = await response.json().catch(() => ({})); if (!response.ok) setMessages((items) => [...items, { who: 'ai', note: true, text: data.code === 'NO_DOCTRINE_SERVICE' ? 'Grounding runs on the edge device. Connect Anchor (set DOCTRINE_BASE_URL) to enable the tutor here.' : (data.error || 'The tutor is unavailable right now.') }]); else if (data.abstained) setMessages((items) => [...items, { who: 'ai', refuse: true, text: data.answer || 'That isn’t supported by the doctrine on this device.', reason: data.abstainReason }]); else setMessages((items) => [...items, { who: 'ai', text: data.answer || '(no answer returned)', citations: Array.isArray(data.citations) ? data.citations : [], meta: data.topScore != null ? `rerank ${Number(data.topScore).toFixed(2)}${data.ms ? ` · ${data.ms}ms` : ''}` : undefined }]); } catch { setMessages((items) => [...items, { who: 'ai', note: true, text: 'Couldn’t reach the tutor. Check your connection and try again.' }]); } finally { setBusy(false); } }
  return <><button className={`scw-fab ask${inCourse ? ' course-context' : ''}`} aria-label="Ask the doctrine" onClick={() => setOpen((value) => !value)}><span className="flab">Ask Doctrine</span><span>?</span></button>{open && <div className={`scw-wgt ask${inCourse ? ' course-context' : ''}`} role="dialog" aria-label="Ask the doctrine"><div className="scw-head"><span className="wi">?</span><div><div className="wt">Ask the doctrine</div><div className="ws">grounded by Anchor · cite-or-refuse</div></div><button className="wx" aria-label="Close" onClick={() => setOpen(false)}>×</button></div><div className="scw-body" ref={chatRef}><div className="scw-chips">{suggestions.map((suggestion) => <button key={suggestion.label} className={`scw-chip${suggestion.refuse ? ' refuse' : ''}`} onClick={() => void send(suggestion.q)}>{suggestion.label}</button>)}</div><div className="scw-chat">{messages.map((message, index) => <div key={index} className={`scw-bubble ${message.who}${message.refuse ? ' refuse' : ''}${message.note ? ' note' : ''}`}><div>{message.text}</div>{message.citations?.map((citation, index) => <div key={index} className="scw-cite"><b>[{citation.n ?? index + 1}]</b> {citation.citation || citation.pub_id || 'source'}{citation.page_printed ? ` · p. ${citation.page_printed}` : ''}</div>)}{message.reason && <div className="scw-meta">not in corpus · {message.reason}</div>}{message.meta && <div className="scw-meta">{message.meta}</div>}</div>)}{busy && <div className="scw-bubble ai">Thinking…</div>}</div></div><div className="scw-foot"><div className="scw-askbar"><input ref={inputRef} className="scw-ti" placeholder="Type a question…" value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void send(); }} /><button className="scw-btn" onClick={() => void send()} disabled={busy || !input.trim()}>Ask</button></div></div></div>}</>;
}