import { useEffect, useState } from 'react';
import { useLocation } from 'wouter';
const types = [{ v: 'bug', label: 'Bug' }, { v: 'idea', label: 'Idea' }, { v: 'question', label: 'Question' }];
const label = (path: string) => path === '/plan' ? 'Planning board' : path.startsWith('/prototype') ? 'App — Student / Instructor' : path;
export default function QaWidget() {
  const [pathname] = useLocation(); const [open, setOpen] = useState(false); const [type, setType] = useState('bug'); const [text, setText] = useState('');
  useEffect(() => { const listener = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false); }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener); }, []);
  const context = `**Where:** ${label(pathname)}\n**URL:** ${typeof window === 'undefined' ? '' : window.location.href}\n**Screen:** ${typeof window === 'undefined' ? '' : `${window.innerWidth}×${window.innerHeight}`}\n**Time:** ${new Date().toISOString()}`;
  const issueUrl = `https://github.com/groundworklms/SchoolCircleLMS/issues/new?title=${encodeURIComponent(`[QA·${type}] ${text.trim().slice(0, 60)}`)}&body=${encodeURIComponent(`**Type:** ${type}\n\n${text.trim()}\n\n---\n${context}\n\n_Opened via the in-app QA widget as a draft._`)}&labels=qa`;
  return <><button className="scw-fab issue" aria-label="Report an issue" onClick={() => setOpen((value) => !value)}><span className="flab">Report an issue (QA)</span><span>!</span></button>{open && <div className="scw-wgt issue" role="dialog" aria-label="Report an issue"><div className="scw-head"><span className="wi">!</span><div><div className="wt">Report an issue</div><div className="ws">opens an issue draft with your location</div></div><button className="wx" aria-label="Close" onClick={() => setOpen(false)}>×</button></div><div className="scw-body"><div className="scw-ctx"><b>Where:</b> {label(pathname)}<br /><b>Screen:</b> {window.innerWidth}×{window.innerHeight}</div><select className="scw-field" value={type} onChange={(event) => setType(event.target.value)}>{types.map((item) => <option key={item.v} value={item.v}>{item.label}</option>)}</select><textarea className="scw-field" placeholder="What did you find, or what needs fixing?" value={text} onChange={(event) => setText(event.target.value)} /><a className={`scw-btn full${text.trim() ? '' : ' disabled'}`} href={text.trim() ? issueUrl : undefined} target="_blank" rel="noopener noreferrer">Open issue draft →</a><p className="scw-note">Captures your view, screen, URL and time in a prefilled GitHub issue draft. Review it there, then submit it.</p></div></div>}</>;
}